services:
  get_data:
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c "sleep 15 && alembic upgrade head 
      && python save_data_to_db.py"
    depends_on:
      - db

  print_data:
    build:
      context: .
    ports:
      - "5000:5000"
    command: >
      sh -c "sleep 5 && python show_data.py"
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env